on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: macos-latest
    env: 
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CI: false
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
    
      - name: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: install_python_deps
        run: pip install -r capture_service/requirements.txt
        
      - name: install_npm_dependencies
        run: npm install
      
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_ENVIRONMENT=${{ secrets.REACT_APP_ENVIRONMENT }} >> .env
          echo REACT_APP_LOGIN_URL=${{ secrets.REACT_APP_LOGIN_URL }} >> .env
          echo REACT_APP_CONTRACTS_URL=${{ secrets.REACT_APP_CONTRACTS_URL }} >> .env
          echo REACT_APP_BOARD_CARDS_URL=${{ secrets.REACT_APP_BOARD_CARDS_URL }} >> .env
          echo REACT_APP_START_SESSION_URL=${{ secrets.REACT_APP_START_SESSION_URL }} >> .env
          echo REACT_APP_SEND_MEMO_URL=${{ secrets.REACT_APP_SEND_MEMO_URL }} >> .env
          echo REACT_APP_END_SESSION_URL=${{ secrets.REACT_APP_END_SESSION_URL }} >> .env
          echo REACT_APP_APPLE_ID=${{ secrets.REACT_APP_APPLE_ID }} >> .env
          echo REACT_APP_APPLE_ID_PASSWORD=${{ secrets.REACT_APP_APPLE_ID_PASSWORD }} >> .env

      - name: Install the Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
      - name: build_python
        run: |
          npm run build-python
          sudo rm -rf capture_service/dist/capture/tk/images
        
      - name: build_react
        run: npm run react-build
        
      - name: build_deploy
        run: npm run electron-build-deploy

      # - name: deploy_release
      #  run: CI=false npm run deploy
      #  env: 
      #    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
